# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Hazir-smart-attendance-management\src\frontend\attendanceSession.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_for_camera_rec = QtWidgets.QWidget(self.centralwidget)
        self.widget_for_camera_rec.setGeometry(QtCore.QRect(30, 30, 581, 361))
        self.widget_for_camera_rec.setObjectName("widget_for_camera_rec")
        self.manual_entry_heading = QtWidgets.QLabel(self.centralwidget)
        self.manual_entry_heading.setGeometry(QtCore.QRect(120, 430, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.manual_entry_heading.setFont(font)
        self.manual_entry_heading.setObjectName("manual_entry_heading")
        self.name_input_box = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input_box.setGeometry(QtCore.QRect(120, 490, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_input_box.setFont(font)
        self.name_input_box.setObjectName("name_input_box")
        self.id_input_box = QtWidgets.QLineEdit(self.centralwidget)
        self.id_input_box.setGeometry(QtCore.QRect(120, 560, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_input_box.setFont(font)
        self.id_input_box.setObjectName("id_input_box")
        self.enter_button = QtWidgets.QPushButton(self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(490, 510, 121, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.enter_button.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enter_button.setFont(font)
        self.enter_button.setObjectName("enter_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.manual_entry_heading.setText(_translate("MainWindow", "Manual Entry"))
        self.name_input_box.setText(_translate("MainWindow", "Name:"))
        self.id_input_box.setText(_translate("MainWindow", "ID:"))
        self.enter_button.setText(_translate("MainWindow", "Enter"))
