# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Danish\Documents\GitHub\Hazir-smart-attendance-management\src\frontend\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_email = QtWidgets.QLineEdit(self.centralwidget)
        self.input_email.setGeometry(QtCore.QRect(270, 250, 201, 31))
        self.input_email.setObjectName("input_email")
        self.input_password = QtWidgets.QLineEdit(self.centralwidget)
        self.input_password.setGeometry(QtCore.QRect(270, 300, 201, 31))
        self.input_password.setObjectName("input_password")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(290, 390, 131, 31))
        self.login_button.setMouseTracking(False)
        self.login_button.setObjectName("login_button")
        self.forgot_pass_button = QtWidgets.QLineEdit(self.centralwidget)
        self.forgot_pass_button.setEnabled(False)
        self.forgot_pass_button.setGeometry(QtCore.QRect(270, 340, 101, 22))
        self.forgot_pass_button.setObjectName("forgot_pass_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_email.setText(_translate("MainWindow", "Email"))
        self.input_password.setText(_translate("MainWindow", "password"))
        self.login_button.setText(_translate("MainWindow", "Log in"))
        self.forgot_pass_button.setText(_translate("MainWindow", "forgot password"))
