# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Hazir-smart-attendance-management\src\home_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Classes.classes import ClassRoom, Student, Teacher
import sys, os, json

# getting the directory path
folder_path = os.getcwd() + "/src"



class Ui_homepage(object):
    currentwindow =None
    
    def setupUi(self, mainwindow, classrooms: list):
        currentwindow = mainwindow
        mainwindow.setObjectName("homepage")
        mainwindow.resize(1000, 700)
        font = QtGui.QFont()
        font.setPointSize(11)
        mainwindow.setFont(font)
        mainwindow.setStyleSheet("background-color:#2f3c7e")
        self.verticalScrollBar = QtWidgets.QScrollBar(mainwindow)
        self.verticalScrollBar.setGeometry(QtCore.QRect(980, 0, 21, 701))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.search_line_edit = QtWidgets.QLineEdit(mainwindow)
        self.search_line_edit.setGeometry(QtCore.QRect(260, 90, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_line_edit.setFont(font)
        self.search_line_edit.setStyleSheet("border-radius:10px;\n"
"background-color:#fbeaeb")
        self.search_line_edit.setObjectName("search_line_edit")
        self.top_widget_2 = QtWidgets.QWidget(mainwindow)
        self.top_widget_2.setGeometry(QtCore.QRect(0, 0, 981, 61))
        self.top_widget_2.setStyleSheet("background-color:#fbeaeb")
        self.top_widget_2.setObjectName("top_widget_2")
        self.back_button = QtWidgets.QPushButton(self.top_widget_2)
        self.back_button.setGeometry(QtCore.QRect(10, 10, 61, 41))
        self.back_button.setIconSize(QtCore.QSize(30, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(folder_path+"/assets/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button.setIcon(icon)
"")
        self.back_button.setText("")
        self.back_button.setObjectName("back_button")
        self.hamburegr_button = QtWidgets.QPushButton(self.top_widget_2)
        self.hamburegr_button.setGeometry(QtCore.QRect(920, 10, 51, 41))
        self.hamburegr_button.setStyleSheet("border-image: url(/Users/Zulfiqar/Pictures/menu.PNG) stretch;\n"
"")
        self.hamburegr_button.setText("")
        self.hamburegr_button.setObjectName("hamburegr_button")
        self.homepageLabel = QtWidgets.QLabel(self.top_widget_2)
        self.homepageLabel.setGeometry(QtCore.QRect(410, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.homepageLabel.setFont(font)
        self.homepageLabel.setObjectName("homepageLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(mainwindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(119, 170, 541, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.filter_button = QtWidgets.QPushButton(mainwindow)
        self.filter_button.setGeometry(QtCore.QRect(550, 90, 51, 41))
        self.filter_button.setStyleSheet("border-image: url(/Users/Zulfiqar/Pictures/clear.PNG) stretch;\n"
"")
        self.filter_button.setText("")
        self.filter_button.setObjectName("filter_button")
        self.add_room_pushButton = QtWidgets.QPushButton(mainwindow)
        self.add_room_pushButton.setGeometry(QtCore.QRect(780, 320, 91, 81))
        self.add_room_pushButton.setStyleSheet("border-image: url(/Users/Zulfiqar/Pictures/ad.PNG) stretch;\n"
"")
        self.add_room_pushButton.setText("")
        self.add_room_pushButton.setObjectName("add_room_pushButton")
        self.homepageLabel_2 = QtWidgets.QLabel(mainwindow)
        self.homepageLabel_2.setGeometry(QtCore.QRect(750, 440, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.homepageLabel_2.setFont(font)
        self.homepageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.homepageLabel_2.setObjectName("homepageLabel_2")

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, homepage):
        _translate = QtCore.QCoreApplication.translate
        homepage.setWindowTitle(_translate("homepage", "Home Page"))
        self.search_line_edit.setPlaceholderText(_translate("homepage", " Search......"))
        self.homepageLabel.setText(_translate("homepage", "Home Page"))
        self.homepageLabel_2.setText(_translate("homepage", "+ Add Room"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homepage = QtWidgets.QWidget()
    ui = Ui_homepage()
    ui.setupUi(homepage)
    homepage.show()
    sys.exit(app.exec_())