from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoomInfo(object):
    def setupUi(self, RoomInfo):
        RoomInfo.setObjectName("RoomInfo")
        RoomInfo.resize(1000, 639)
        RoomInfo.setStyleSheet("background-color:#2f3c7e")
        self.widget = QtWidgets.QWidget(RoomInfo)
        self.widget.setGeometry(QtCore.QRect(40, 130, 401, 471))
        self.widget.setStyleSheet("background-color:#fbeaeb;\n"
"border-radius:30px;")
        self.widget.setObjectName("widget")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 330, 101, 101))
        self.pushButton_2.setStyleSheet("border-image: url(/Users/Zulfiqar/Pictures/u2.PNG) stretch;\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.roomdetailsLabel_2 = QtWidgets.QLabel(self.widget)
        self.roomdetailsLabel_2.setGeometry(QtCore.QRect(110, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.roomdetailsLabel_2.setFont(font)
        self.roomdetailsLabel_2.setStyleSheet("border:2px solid black;\n"
"border-radius: 10px;")
        self.roomdetailsLabel_2.setObjectName("roomdetailsLabel_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(29, 110, 341, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.addmemberLabel_3 = QtWidgets.QLabel(self.widget)
        self.addmemberLabel_3.setGeometry(QtCore.QRect(240, 430, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addmemberLabel_3.setFont(font)
        self.addmemberLabel_3.setStyleSheet("border:none;")
        self.addmemberLabel_3.setObjectName("addmemberLabel_3")
        self.widget_2 = QtWidgets.QWidget(RoomInfo)
        self.widget_2.setGeometry(QtCore.QRect(-1, 0, 1001, 51))
        self.widget_2.setStyleSheet("background-color:#fbeaeb")
        self.widget_2.setObjectName("widget_2")
        self.hometitleLabel = QtWidgets.QLabel(self.widget_2)
        self.hometitleLabel.setGeometry(QtCore.QRect(460, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.hometitleLabel.setFont(font)
        self.hometitleLabel.setStyleSheet("border:2px solid black;\n"
"border-radius: 10px;")
        self.hometitleLabel.setObjectName("hometitleLabel")
        self.bread_crumbs_label = QtWidgets.QLabel(self.widget_2)
        self.bread_crumbs_label.setGeometry(QtCore.QRect(80, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bread_crumbs_label.setFont(font)
        self.bread_crumbs_label.setObjectName("bread_crumbs_label")

        self.hamburegrbutton = QtWidgets.QPushButton(self.widget_2)
        self.hamburegrbutton.setGeometry(QtCore.QRect(940, 0, 61, 51))
        # self.hamburegrbutton.setGeometry(QtCore.QRect(880, 0, 100, 51))
        self.hamburegrbutton.setStyleSheet("border-image: url(/Users/Zulfiqar/Pictures/menu.PNG) stretch;\n"
"") 
        self.hamburegrbutton.clicked.connect(self.show_hamburger_menu)
        self.hamburegrbutton.setText("")
        self.hamburegrbutton.setObjectName("hamburegrbutton")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 0, 51, 51))
        self.pushButton.setStyleSheet("border-image: url(/Users/Zulfiqar/Pictures/previous.PNG) stretch;\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.start_seesion_button = QtWidgets.QPushButton(RoomInfo)
        self.start_seesion_button.setGeometry(QtCore.QRect(620, 260, 221, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.start_seesion_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_seesion_button.setFont(font)
        self.start_seesion_button.setStyleSheet("background-color:#fbeaeb;\n"
"color: black;\n"
"border-radius:10px;\n"
"border:none;\n"
"")
        self.start_seesion_button.setObjectName("start_seesion_button")
        self.get_last_report_button = QtWidgets.QPushButton(RoomInfo)
        self.get_last_report_button.setGeometry(QtCore.QRect(620, 400, 221, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 60, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.get_last_report_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.get_last_report_button.setFont(font)
        self.get_last_report_button.setStyleSheet("background-color:#b1b40a;\n"
"color: black;\n"
"border-radius:10px;\n"
"border:none;\n"
"")
        self.get_last_report_button.setObjectName("get_last_report_button")
        self.userpic = QtWidgets.QLabel(RoomInfo)
        self.userpic.setGeometry(QtCore.QRect(630, 270, 61, 61))
        self.userpic.setText("")
        self.userpic.setPixmap(QtGui.QPixmap("../../Users/Zulfiqar/Downloads/session(new).png"))
        self.userpic.setScaledContents(True)
        self.userpic.setObjectName("userpic")
        self.userpic_2 = QtWidgets.QLabel(RoomInfo)
        self.userpic_2.setGeometry(QtCore.QRect(630, 410, 61, 61))
        self.userpic_2.setText("")
        self.userpic_2.setPixmap(QtGui.QPixmap("../../Users/Zulfiqar/Downloads/report(new).png"))
        self.userpic_2.setScaledContents(True)
        self.userpic_2.setObjectName("userpic_2")
    def show_hamburger_menu(self):
        menu = QtWidgets.QMenu(self.widget_2)
        menu.setFixedWidth(150)
        menu.setFixedHeight(150)
        # Adjust the x-coordinate to shift the menu towards the left
        position = QtCore.QPoint(-150, self.hamburegrbutton.height() + 10)
        position = QtCore.QPoint(-25, self.hamburegrbutton.height() + 10)
        edit_profile_action = menu.addAction("Edit Profile")
        add_room_action = menu.addAction("Edit\Add Room")
        add_member_action = menu.addAction("Add Member")
        condition=menu.addAction("Terms and conditions")
        logout_action = menu.addAction("Logout")
        # Set a fixed width and height for the menu
        action = menu.exec_(self.hamburegrbutton.mapToGlobal(position))
      
        # action = menu.exec_(self.hamburegrbutton.mapToGlobal(QtCore.QPoint(0, self.hamburegrbutton.height())))
#         
        if action == edit_profile_action:
            # Handle "Edit Profile" action
            print("Edit Profile")
        elif action == add_room_action:
            # Handle "Add Room" action
            print("Add Room")
        elif action == add_member_action:
            # Handle "Add Member" action
            print("Add Member")
        elif action == logout_action:
            # Handle "Logout" action
            print("Logout")
        elif action== condition:
            print("conditions clicked")    

        self.retranslateUi(RoomInfo)
        QtCore.QMetaObject.connectSlotsByName(RoomInfo)

    def retranslateUi(self, RoomInfo):
        _translate = QtCore.QCoreApplication.translate
        RoomInfo.setWindowTitle(_translate("RoomInfo", "Room Information"))
        self.roomdetailsLabel_2.setText(_translate("RoomInfo", "    Room Details"))
        self.addmemberLabel_3.setText(_translate("RoomInfo", "    Add Member"))
        self.hometitleLabel.setText(_translate("RoomInfo", "    Room Title"))
        self.bread_crumbs_label.setText(_translate("RoomInfo", "HomePage->RoomInformation"))
        self.start_seesion_button.setText(_translate("RoomInfo", "           Start Session"))
        self.get_last_report_button.setText(_translate("RoomInfo", "                Get Last Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoomInfo = QtWidgets.QDialog()
    ui = Ui_RoomInfo()
    ui.setupUi(RoomInfo)
    RoomInfo.show()
    sys.exit(app.exec_())